//****************************************************
// Company : Rochester Institute of Technology (RIT )
// Engineer : Ryan Hall (rah3587@rit.edu)
//
// Create Date : 10/6/26
// Design Name : coef_rom
// Module Name : coef_rom 
// Project Name : FIR_Filter
// Target Devices : Basys3
//
// Description : ROM to hold coefficients and channel select, input tap_index and output
// tap_out used to access individual taps
//****************************************************
module coef_rom #(
    parameter COEF_WIDTH = 16,
    parameter TAP_COUNT = 59
)(
    input wire  clk,                  // Rising edge enabled clock
    input wire  [1:0] ch_select,      // Select Channel 1/2/3
    input wire  [$clog2(TAP_COUNT)-1:0] tap_index,  // Select tap (0-58)
    output reg signed [COEF_WIDTH-1:0] tap_out      // Output tap value
);

    // core should never call indicies 59:63
    reg signed [COEF_WIDTH-1:0] coef_ch1 [0:TAP_COUNT-1];     // Coefficients to allow channel 1
    reg signed [COEF_WIDTH-1:0] coef_ch2 [0:TAP_COUNT-1];    // Coefficients to allow channel 2
    reg signed [COEF_WIDTH-1:0] coef_ch3 [0:TAP_COUNT-1];   // Coefficients to allow channel 3 

    // Initialize values to memory from file generated by matlab
    initial begin
        $readmemh("coef_ch1.hex", coef_ch1);
        $readmemh("coef_ch2.hex", coef_ch2);
        $readmemh("coef_ch3.hex", coef_ch3);
    end

    always @(posedge clk) begin       
        case (ch_select)
            2'b01:   tap_out <= coef_ch1[tap_index];     // select = 1: channel 1
            2'b10:   tap_out <= coef_ch2[tap_index];     // select = 2: channel 2
            2'b11:   tap_out <= coef_ch3[tap_index];     // select = 3: channel 3
            default: tap_out <= {COEF_WIDTH{1'b0}};                // default:    no signal
        endcase
    end
endmodule



